# Generated by Django 4.2 on 2026-02-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0002_faculty_department_alter_attendance_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
