# Generated by Django 3.2 on 2026-02-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0003_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
