# Generated by Django 3.2 on 2026-02-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0005_alter_attendance_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos/'),
        ),
    ]
