# Generated by Django 3.2 on 2026-02-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0007_book_messtransaction_messwallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messtransaction',
            name='meal_type',
            field=models.CharField(default='Meal', max_length=50),
        ),
    ]
