# Generated by Django 3.2 on 2026-02-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0009_bookissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_present',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date')},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='course',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='status',
        ),
    ]
