# Generated by Django 3.2 on 2026-02-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0011_auto_20260205_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
