# Generated by Django 3.2 on 2026-02-09 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0013_auto_20260206_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(editable=False, max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_type', models.CharField(choices=[('Tuition', 'Tuition Fee'), ('Exam', 'Exam Fee'), ('Hostel', 'Hostel Fee'), ('Library', 'Library Fee')], max_length=50)),
                ('date_paid', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='Paid', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='campus.student')),
            ],
        ),
    ]
