# Generated by Django 3.2 on 2026-02-13 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0016_complaint_leaveapplication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
