# Generated by Django 3.2 on 2026-02-13 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campus', '0017_delete_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Electricity', 'Electricity'), ('Water/Plumbing', 'Water/Plumbing'), ('Wi-Fi/Internet', 'Wi-Fi/Internet'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='hostelroom',
            old_name='room_no',
            new_name='room_number',
        ),
        migrations.RemoveField(
            model_name='leaveapplication',
            name='status',
        ),
        migrations.AlterField(
            model_name='hostelroom',
            name='student',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='HostelComplaint',
        ),
    ]
