# Generated by Django 3.2 on 2026-03-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0022_feetransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
