# Generated by Django 3.2 on 2026-03-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0023_leaveapplication_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='created_at',
            new_name='date_posted',
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='content',
            new_name='message',
        ),
        migrations.AddField(
            model_name='notice',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
    ]
