# Generated by Django 3.2 on 2026-03-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0024_auto_20260317_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='events/')),
                ('date', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
